services:

  db:
    image: postgres:18
    restart: always
    shm_size: 128mb
    volumes:
      - pg-data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:5432'

  db-test:
    image: postgres:18
    shm_size: 128mb
    tmpfs:
      - /var/lib/postgresql
    command: >
      postgres -c fsync=off -c full_page_writes=off -c synchronous_commit=off
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:5432'

volumes:
  pg-data:
