packages:
  - 'apps/*'
  - 'libs/*'
allowBuilds:
  '@nestjs/core': true
  '@scarf/scarf': true
  '@swc/core': true
  cpu-features: true
  esbuild: true
  nx: true
  protobufjs: true
  ssh2: true
  unrs-resolver: true
